version: '3'
services:
  core:
    restart: always
    image: nginx
    ports:
      - "127.0.0.1:8081:8080"
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/core_self_signed:/etc/sswc
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      - ./data/www:/var/www

